FROM panther.centraldg6.athens.intrasoft-intl.private:32443/ermis-tn-external-libs/oracle-db:12.2.0.1-slim

WORKDIR /home/oracle/setup/custom_scripts

COPY database-migration/src/main/resources/liquibase/sender-app-db-config/configDBora.sh /home/oracle/setup/
